spring:
  application:
    name: chat
  data:
    redis:
      host: localhost
      port: 6379
logging:
  level:
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG

face:
  service:
    url: http://localhost:8000
jwt:
  secret: BxsmVbElz3wP7iqRPIxnLSCuc1xJ890ymIPrvtkheXny6NZtiaWzIHOefrBoKIp5
  expiration-ms: ${JWT_EXPIRATION_MS:8760}
  issuer: gener.chat